### ISSUE TITLE
Storing data outside EU

### ISSUE THREAD

**Issue by cbwheadon** [NoMoreMarking/terms-of-service#1]
We say this:
<img width="483" alt="screen shot 2018-04-19 at 11 38 14" src="https://user-images.githubusercontent.com/537793/38987028-4eafa59a-43c6-11e8-925c-b3d6ac97384e.png">
but if cloudinary stores images with pupil names on outside the EU - aren't we contradicting ourselves?

**Comment by cbwheadon** [comment]
Perhaps we should reference this: https://cloudinary.com/privacy#section_privacy_shield

**Comment by BrianSHenderson** [comment]
I'm assuming AWS only use countries which have 'Adequate Levels of Protection'?
![screen shot 2018-04-19 at 12 10 15](https://user-images.githubusercontent.com/2174330/38988311-aa01f55c-43ca-11e8-934d-46cc36f9435b.png)
