### ISSUE TITLE
POP terms and conditions

### ISSUE THREAD

**Issue by cbwheadon** [NoMoreMarking/terms-of-service#3]
Remove all references to FFT Aspire:

As part of the Services, NMM may provide optional analyses of the assessment results which are linked to pupil data in FFT Aspire. In order for NMM to provide these optional analyses, the Customer shall ensure that the individuals whose information is submitted in accordance with the Services, or the parents/guardians of such individuals in the case of the submission of information of minor children, have been notified about the linking of the assessment results data to other data in FFT Aspire, and have been given the option to opt out if they/their parents/guardians do not wish their data to be linked to other pupil data in FFT Aspire.

**Comment by BrianSHenderson** [comment]
That's updated
